In [17]:
import pandas as pd

# TSC

In [18]:
tsc_datasets = [
   'BeetleFly',
   'ACSF1',
   'CricketX',
   'CinCECGTorso',
   'LSST'
]
feat_time = pd.read_csv('../../tsc/outputs/time_multi.csv')
feat = (
    feat_time.rename(columns={'time_seconds': 'time'})
    .loc[feat_time['dataset'].isin(tsc_datasets), ['dataset', 'time']]
    .reset_index(drop=True)
)
feat

        dataset     time
0         ACSF1   3.5136
1     BeetleFly   0.3849
2  CinCECGTorso  40.7702
3      CricketX   5.2152
4          LSST   6.1068

In [19]:
inference_time = pd.read_csv('../../tsc/outputs/multi.csv')[['dataset', 'time']]
inference = inference_time[inference_time['dataset'].isin(tsc_datasets)].groupby('dataset', as_index=False)['time'].mean().reset_index(drop=True)
inference

        dataset         time
0         ACSF1    62.743151
1     BeetleFly    62.336064
2  CinCECGTorso    68.334693
3      CricketX   571.119034
4          LSST  1037.863436

In [20]:
(feat.set_index('dataset')['time'] + inference.set_index('dataset')['time']).reset_index()

        dataset         time
0         ACSF1    66.256751
1     BeetleFly    62.720964
2  CinCECGTorso   109.104893
3      CricketX   576.334234
4          LSST  1043.970236

# TSER

In [21]:
tser_datasets = [
   'Covid3Month',
   'FloodModeling3',
   'HouseholdPowerConsumption1_nmv',
   'IEEEPPG',
   'BIDMC32SpO2'
]
feat_time = pd.read_csv('../../tser/outputs/time_tsfresh.csv')
feat = (
    feat_time.rename(columns={'time_seconds': 'time'})
    .loc[feat_time['dataset'].isin(tser_datasets), ['dataset', 'time']]
    .reset_index(drop=True)
)
feat

                          dataset        time
0                     Covid3Month      1.7597
1                  FloodModeling3      5.9115
2                         IEEEPPG   2917.9472
3  HouseholdPowerConsumption1_nmv   1931.0186
4                     BIDMC32SpO2  14376.4730

In [22]:
inference_time = pd.read_csv('../../tser/outputs/tsfresh.csv')[['dataset', 'time']]
inference = inference_time[inference_time['dataset'].isin(tser_datasets)].groupby('dataset', as_index=False)['time'].mean().reset_index(drop=True)
inference

                          dataset       time
0                     BIDMC32SpO2  86.943870
1                     Covid3Month   2.281774
2                  FloodModeling3   5.125048
3  HouseholdPowerConsumption1_nmv  12.879475
4                         IEEEPPG  28.526290

In [23]:
(feat.set_index('dataset')['time'] + inference.set_index('dataset')['time']).reset_index()

                          dataset          time
0                     BIDMC32SpO2  14463.416870
1                     Covid3Month      4.041474
2                  FloodModeling3     11.036548
3  HouseholdPowerConsumption1_nmv   1943.898075
4                         IEEEPPG   2946.473490